name: Citadel
main: com.untamedears.citadel.Citadel
version: 2.5.24
description: Reinforce your structures!
author: chrisrico, jonnyd (aka Gu3rr1lla)
database: false
commands:
  ctmaterials:
    aliases: ctmat
    description: List the possible reinforcement materials, their strengths, and requirements.
    usage: /ctmaterials (or /ctmat)
  ctsecurable:
    aliases: cts
    description: Other than containers and doors, lists the blocks which are securable.
    usage: /ctsecurable (or /cts)
  ctnonreinforceable:
    aliases: ctn
    description: Lists the blocks which may not be reinforced.
    usage: /ctnonreinforceable (or /ctn)
  ctreinforce:
    aliases: ctr
    description: The blocks you interact with will be reinforced with the material in hand.
    usage: /ctreinforce (or /ctr) [security level]
  ctfortify:
    aliases: ctf
    description: Each placed block is reinforced with the material in hand at the time of the command.
    usage: /ctfortify (or /ctf) [security level]
  ctinfo:
    aliases: cti
    description: While in this mode, punching a block gives you information about it's reinforcement and security level.
    usage: /ctinfo (or /cti)
  ctinsecure:
    aliases: ctis
    description: While in this mode, punching a reinforcement toggles its insecure status.
    usage: /ctinsecure (or /ctis)
  ctoff:
    aliases: cto
    description: Turns off reinforcement, fortification, and info mode.
    usage: /ctoff (or /cto)
  ctbypass:
    aliases: ctb
    description: Toggles bypassing your own reinforcements to break blocks normally.
    usage: /ctbypass (or /ctb)
  ctpublic:
    aliases: ctpu
    description: The next door/container you interact with will become publicly secured.
    usage: /ctpublic (or /ctpu)
  ctprivate:
    aliases: ctpr
    description: The next door/container you interact with will become privately secured.
    usage: /ctprivate (or /ctpr)
  ctgroup:
    aliases: ctg
    description: The next door/container you interact with will become secured to your group.
    usage: /ctgroup (or /ctg) <group-name>
  ctcreate:
    aliases: ctc
    description: Creates a group.
    usage: /ctcreate (or /ctc) <group-name>
  ctdelete:
    aliases: ctdel
    description: Deletes a group.
    usage: /ctdelete (or /ctdel) <group-name>
  ctgroups:
    aliases: ctgs
    description: Lists your groups.
    usage: /ctgroups (or /ctgs)
  ctmembers:
    aliases: ctm
    description: Lists the players in your group.
    usage: /ctmembers (or /ctm) <group-name>
  ctallow:
    aliases: cta
    description: Adds the specified player to your group.
    usage: /ctallow (or /cta) <group-name> <player-name>
  ctdisallow:
    aliases: ctd
    description: Removes the specified player from your group.
    usage: /ctdisallow (or /ctd) <group-name> <player-name>
  ctversion:
    aliases: ctv
    description: Displays plugin version.
    usage: /ctversion (or /ctv)
  ctstats:
    description: Displays stats.
    usage: /ctstats
  ctleave:
    aliases: ctl
    description: Leave a group.
    usage: /ctleave (or /ctl)
  ctjoin:
    aliases: ctj
    description: Joins a group.
    usage: /ctjoin (or /ctj) <group-name> <password>
  ctpassword:
    aliases: ctpw
    description: Sets a groups password.
    usage: /ctpassword (or /ctpw) <group-name> <password>
  cttransfer:
    aliases: ctt
    description: Transfers a group to another player.
    usage: /cttransfer (or /ctt) <group-name> <player-name>
  ctaddmod:
    aliases: ctam
    description: Adds a player as moderator to a group.
    usage: /ctaddmod (or /ctam) <group-name> <player-name>
  ctremovemod:
    aliases: ctrm
    description: Removes a player as moderator from a group.
    usage: /ctremovemod (or /ctrm) <group-name> <player-name>
  ctmoderators:
    aliases: ctmods
    description: Displays moderators of a group.
    usage: /ctmoderators (or /ctmods) <group-name>
  ctgroupinfo:
    aliases: ctgi
    description: Displays information about a group.
    usage: /ctgroupinfo (or /ctgi) <group-name>
  ctgstats:
    aliases: ctgst
    description: Displays group statistics
    usage: /ctgstats <group-name>
  ctcon:
    description: Restricted console commands
    usage: /ctcon
    permission: citadel.console
  ctpstats:
    aliases: ctpst
    description: Displayers player statistics
    usage: /ctpstats <player-name>
    permission: citadel.admin.ctpstats
  ctdiscipline:
    aliases: ctadg
    description: Disciplines a group
    usage: /ctdiscipline [del] <group-name>
    permission: citadel.admin.ctdiscipline
  ctreprieve:
    aliases: ctarg
    description: Reprieves a group
    usage: /ctreprieve <group-name>
    permission: citadel.admin.ctreprieve
  ctacid:
    description: Trigger acid block to eat a reinforcement
    usage: /ctacid
    permission: citadel.ctacid
  ctmature:
    description: Instantly mature a reinforcement
    usage: /ctmature
permissions:
  citadel.console:
    description: Console commands for Citadel
    default: false
  citadel.admin:
    description: Grants permission to Citadels admin commands.
    default: op
    children:
      citadel.admin.ctgstats: true
      citadel.admin.ctpstats: true
      citadel.admin.ctdiscipline: true
      citadel.admin.ctreprieve: true
      citadel.admin.ctinfodetails: true
      citadel.admin.accesssecurable: true
      citadel.admin.cttransfer: true
      citadel.admin.reassignreinforcements: true
      citadel.admin.bypassmode: true
  citadel.ctacid:
    description: Allow /ctacid
    default: true
